export const FEATURES = {
  '0': { id: 0, title: 'FAVORITES', category: 'CONTROL', source: 'PC', desc: 'Media + lock + screenshot', actions: [{ label: 'PLAY/PAUSE', command: 'MEDIA_PLAY_PAUSE' }, { label: 'MUTE', command: 'MEDIA_MUTE' }, { label: 'LOCK', command: 'PC_LOCK' }, { label: 'SHOT', command: 'SCREENSHOT' }] },
  '1': { id: 1, title: 'PC MONITOR', category: 'CONTROL', source: 'PC', desc: 'CPU / RAM / PC status from PC agent', actions: [{ label: 'REFRESH', command: 'GET_PC_STATUS' }] },
  '2': { id: 2, title: 'NOW PLAYING', category: 'CONTROL', source: 'PC', desc: 'Media transport control', actions: [{ label: 'PREV', command: 'MEDIA_PREV' }, { label: 'PLAY', command: 'MEDIA_PLAY_PAUSE' }, { label: 'NEXT', command: 'MEDIA_NEXT' }, { label: 'MUTE', command: 'MEDIA_MUTE' }] },
  '3': { id: 3, title: 'AI LIMITS', category: 'SMART', source: 'PHONE', desc: 'AI usage snapshot via phone provider', actions: [{ label: 'REFRESH', command: 'PHONE_REFRESH_AI' }] },
  '4': { id: 4, title: 'CONTEXT AWARE', category: 'SMART', source: 'PHONE', desc: 'PC context suggestions with manual execution', actions: [{ label: 'REFRESH', command: 'CONTEXT_REFRESH' }, { label: 'FOCUS', command: 'DEEP_FOCUS' }] },
  '5': { id: 5, title: 'AIR MOUSE', category: 'CONTROL', source: 'PC', desc: 'Mouse controls from the wrist', actions: [{ label: 'L-CLICK', command: 'MOUSE_LEFT' }, { label: 'R-CLICK', command: 'MOUSE_RIGHT' }, { label: 'UP', command: 'SCROLL_UP' }, { label: 'DOWN', command: 'SCROLL_DOWN' }] },
  '6': { id: 6, title: 'APP LAUNCHER', category: 'APPS', source: 'PC', desc: 'Launch whitelisted Windows apps', actions: [{ label: 'CHROME', command: 'APP_CHROME' }, { label: 'VS CODE', command: 'APP_VSCODE' }, { label: 'STEAM', command: 'APP_STEAM' }, { label: 'DISCORD', command: 'APP_DISCORD' }] },
  '7': { id: 7, title: 'D-PAD', category: 'CONTROL', source: 'PC', desc: 'Keyboard navigation', actions: [{ label: 'UP', command: 'KEY_UP' }, { label: 'LEFT', command: 'KEY_LEFT' }, { label: 'RIGHT', command: 'KEY_RIGHT' }, { label: 'DOWN', command: 'KEY_DOWN' }] },
  '8': { id: 8, title: 'SMART ROOM', category: 'SMART', source: 'PHONE', desc: 'Phone/IoT scene provider', actions: [{ label: 'WORK', command: 'IOT_SCENE_WORK' }, { label: 'MOVIE', command: 'IOT_SCENE_MOVIE' }] },
  '9': { id: 9, title: 'PRO TOOLS', category: 'CONTROL', source: 'PC', desc: 'Windows productivity shortcuts', actions: [{ label: 'DESKTOP', command: 'SHOW_DESKTOP' }, { label: 'ALT+TAB', command: 'ALT_TAB' }, { label: 'SNIP', command: 'SCREENSHOT' }, { label: 'LOCK', command: 'PC_LOCK' }] },
  '10': { id: 10, title: 'SYSTEM', category: 'SYSTEM', source: 'WATCH', desc: 'Connection and app power settings', actions: [{ label: 'BALANCED', command: 'POWER_BALANCED' }, { label: 'ENDURANCE', command: 'POWER_ENDURANCE' }, { label: 'HAPTIC', command: 'HAPTIC_TEST' }] },
  '11': { id: 11, title: 'STREAM HUB', category: 'APPS', source: 'PC', desc: 'OBS control bridge', actions: [{ label: 'SCENE 1', command: 'OBS_SCENE_1' }, { label: 'SCENE 2', command: 'OBS_SCENE_2' }, { label: 'MIC', command: 'OBS_TOGGLE_MUTE' }] },
  '12': { id: 12, title: 'NETWORK', category: 'NETWORK', source: 'PHONE', desc: 'Phone connectivity and network handoff', actions: [{ label: 'STATUS', command: 'PHONE_NETWORK_STATUS' }, { label: 'WI-FI', command: 'WIFI_SCAN' }] },
  '14': { id: 14, title: 'TERMINAL', category: 'CONTROL', source: 'PC', desc: 'Safe fixed keyboard macros only', actions: [{ label: 'CTRL+C', command: 'CTRL_C' }, { label: 'CTRL+V', command: 'CTRL_V' }, { label: 'ALT+TAB', command: 'ALT_TAB' }, { label: 'WIN+D', command: 'SHOW_DESKTOP' }] },
  '15': { id: 15, title: 'CAMERA PRO', category: 'APPS', source: 'PHONE', desc: 'Remote phone camera controls', actions: [{ label: 'SHUTTER', command: 'PHONE_CAMERA_SHUTTER' }, { label: 'TIMER', command: 'PHONE_CAMERA_TIMER' }] },
  '18': { id: 18, title: 'ASSET RADAR', category: 'SMART', source: 'PHONE', desc: 'Market data snapshot provider', actions: [{ label: 'REFRESH', command: 'PHONE_REFRESH_MARKET' }] },
  '21': { id: 21, title: 'COMMAND SYSTEM', category: 'CONTROL', source: 'PC', desc: 'Primary PC command center', actions: [{ label: 'BATTLE', command: 'BATTLE_STATION' }, { label: 'FOCUS', command: 'DEEP_FOCUS' }, { label: 'LOCK', command: 'PC_LOCK' }, { label: 'WI-FI', command: 'WIFI_SCAN' }] },
  '23': { id: 23, title: 'PROTOCOLS', category: 'SMART', source: 'PC', desc: 'Whitelisted PC automation protocols', actions: [{ label: 'BATTLE', command: 'BATTLE_STATION' }, { label: 'FOCUS', command: 'DEEP_FOCUS' }] },
  '25': { id: 25, title: 'SYSTEM LOG', category: 'SYSTEM', source: 'WATCH', desc: 'Local PC Remote Deck event status', actions: [{ label: 'CLEAR', command: 'LOG_CLEAR' }] },
  '26': { id: 26, title: 'MOTION COMMAND', category: 'SMART', source: 'WATCH', desc: 'Gesture remote: next, previous, play/pause and mute', actions: [{ label: 'ARM', command: 'MOTION_ARM' }, { label: 'CALIBRATE', command: 'MOTION_CALIBRATE' }, { label: 'DISARM', command: 'MOTION_DISARM' }] },
  '31': { id: 31, title: 'VOICE COMMAND', category: 'SMART', source: 'PHONE', desc: 'Push-to-talk with intent whitelist', actions: [{ label: 'PUSH TO TALK', command: 'VOICE_PTT' }] },
  '39': { id: 39, title: 'WI-FI RECON', category: 'NETWORK', source: 'PHONE', desc: 'Android scans and classifies nearby Wi-Fi for the watch', actions: [{ label: 'SCAN', command: 'WIFI_SCAN' }, { label: 'BEST', command: 'WIFI_BEST' }, { label: 'FREE', command: 'WIFI_FREE' }, { label: 'STATUS', command: 'WIFI_STATUS' }] }
};

export function getFeature(id) {
  return FEATURES[String(id)] || null;
}
