export const FEATURES = {
  '0':  { id:0,  title:'FAVORITES', category:'CONTROL', source:'PC', desc:'Dynamic Home quick actions, media, lock, screenshot and context-aware controls.', actions:[{label:'PLAY',command:'MEDIA_PLAY_PAUSE'},{label:'MUTE',command:'MEDIA_MUTE'},{label:'LOCK',command:'PC_LOCK'},{label:'SHOT',command:'SCREENSHOT'}] },
  '1':  { id:1,  title:'PC MONITOR PRO 2.0', category:'CONTROL', source:'PC', desc:'Real telemetry, 1/3/5 minute history, process ranking, temperatures when available and duration-based alerts.', actions:[{label:'LIVE',command:'GET_DASHBOARD_PRO'},{label:'HISTORY',command:'GET_TELEMETRY_HISTORY'},{label:'PROCESS',command:'GET_TOP_PROCESSES'},{label:'HUB',command:'GET_CONTROL_HUB'}] },
  '2':  { id:2,  title:'NOW PLAYING', category:'CONTROL', source:'PC', desc:'Media transport plus current master audio state.', actions:[{label:'PREV',command:'MEDIA_PREV'},{label:'PLAY',command:'MEDIA_PLAY_PAUSE'},{label:'NEXT',command:'MEDIA_NEXT'},{label:'MUTE',command:'MEDIA_MUTE'}] },
  '3':  { id:3,  title:'AI LIMITS', category:'SMART', source:'PHONE', desc:'Existing phone provider extension point retained for compatibility.', actions:[{label:'REFRESH',command:'PHONE_REFRESH_AI'}] },
  '4':  { id:4,  title:'CONTEXT ENGINE 2.0', category:'SMART', source:'PC', desc:'Detects browser, coding, game, meeting, media, presentation, desktop and manual contexts.', actions:[{label:'REFRESH',command:'GET_CONTEXT_PRO'},{label:'AUTO',command:'CONTEXT_MODE_AUTO'},{label:'MANUAL',command:'CONTEXT_MODE_MANUAL'},{label:'LOCK',command:'CONTEXT_LOCK_TOGGLE'}] },
  '5':  { id:5,  title:'AIR MOUSE PRO 3.0', category:'CONTROL', source:'WATCH+PC', desc:'Auto calibration, acceleration profiles, precision mode, drag/drop, double click and scroll.', actions:[{label:'START',command:'AIR_MOUSE_START'},{label:'PRECISION',command:'AIR_MOUSE_PRECISION'},{label:'DRAG',command:'AIR_MOUSE_DRAG_TOGGLE'},{label:'DOUBLE',command:'AIR_MOUSE_DOUBLE'}] },
  '6':  { id:6,  title:'APP LAUNCHER PRO 2.0', category:'APPS', source:'PC', desc:'Pinned, recent, favorites, running indicator and smart launch/focus behavior.', actions:[{label:'REFRESH',command:'GET_APPS_PRO'},{label:'CHROME',command:'APP_SMART_CHROME'},{label:'VS CODE',command:'APP_SMART_VSCODE'},{label:'STEAM',command:'APP_SMART_STEAM'}] },
  '7':  { id:7,  title:'D-PAD', category:'CONTROL', source:'PC', desc:'Keyboard navigation remote.', actions:[{label:'UP',command:'KEY_UP'},{label:'LEFT',command:'KEY_LEFT'},{label:'RIGHT',command:'KEY_RIGHT'},{label:'DOWN',command:'KEY_DOWN'}] },
  '8':  { id:8,  title:'SMART ROOM', category:'SMART', source:'PHONE', desc:'Existing phone/IoT scene provider retained; provider data is never fabricated.', actions:[{label:'WORK',command:'IOT_SCENE_WORK'},{label:'MOVIE',command:'IOT_SCENE_MOVIE'}] },
  '9':  { id:9,  title:'PRO TOOLS', category:'CONTROL', source:'PC', desc:'Desktop, task switching, screenshot and PC lock quick tools.', actions:[{label:'DESKTOP',command:'SHOW_DESKTOP'},{label:'ALT+TAB',command:'ALT_TAB'},{label:'SNIP',command:'SCREENSHOT'},{label:'LOCK',command:'PC_LOCK'}] },
  '10': { id:10, title:'SYSTEM', category:'SYSTEM', source:'WATCH+PC', desc:'Connection, battery, agent state, power profile and command lifecycle.', actions:[{label:'SYNC',command:'GET_DASHBOARD_PRO'},{label:'EVENTS',command:'GET_EVENTS'},{label:'PERMS',command:'GET_PERMISSIONS'},{label:'PROFILE',command:'GET_PROFILES'}] },
  '11': { id:11, title:'STREAM HUB', category:'APPS', source:'PC', desc:'Existing OBS bridge extension point retained.', actions:[{label:'SCENE 1',command:'OBS_SCENE_1'},{label:'SCENE 2',command:'OBS_SCENE_2'},{label:'MIC',command:'OBS_TOGGLE_MUTE'}] },
  '12': { id:12, title:'NETWORK COMMAND', category:'NETWORK', source:'PC+PHONE', desc:'LAN IP, gateway, DNS, throughput, latency and connection-quality view.', actions:[{label:'STATUS',command:'GET_NETWORK'},{label:'PING',command:'NETWORK_PING'},{label:'WI-FI',command:'WIFI_SCAN'},{label:'HUB',command:'GET_CONTROL_HUB'}] },
  '14': { id:14, title:'TERMINAL MACROS', category:'CONTROL', source:'PC', desc:'Fixed safe keyboard macros retained.', actions:[{label:'CTRL+C',command:'CTRL_C'},{label:'CTRL+V',command:'CTRL_V'},{label:'ALT+TAB',command:'ALT_TAB'},{label:'WIN+D',command:'SHOW_DESKTOP'}] },
  '15': { id:15, title:'CAMERA PRO', category:'APPS', source:'PHONE', desc:'Existing phone camera provider extension point retained.', actions:[{label:'SHUTTER',command:'PHONE_CAMERA_SHUTTER'},{label:'TIMER',command:'PHONE_CAMERA_TIMER'}] },
  '18': { id:18, title:'ASSET RADAR', category:'SMART', source:'PHONE', desc:'Existing phone market-data provider extension point retained.', actions:[{label:'REFRESH',command:'PHONE_REFRESH_MARKET'}] },
  '21': { id:21, title:'COMMAND CENTER PRO', category:'CONTROL', source:'PC', desc:'Unified PC control hub with online state, telemetry, context, active app and quick actions.', actions:[{label:'HUB',command:'GET_CONTROL_HUB'},{label:'FOCUS',command:'DEEP_FOCUS'},{label:'BATTLE',command:'BATTLE_STATION'},{label:'LOCK',command:'PC_LOCK'}] },
  '23': { id:23, title:'PROTOCOL ENGINE V2', category:'SMART', source:'PC', desc:'Whitelisted multi-step protocol execution integrated with the event bus.', actions:[{label:'BATTLE',command:'BATTLE_STATION'},{label:'FOCUS',command:'DEEP_FOCUS'},{label:'MACROS',command:'GET_MACROS_V2'},{label:'EVENTS',command:'GET_EVENTS'}] },
  '25': { id:25, title:'SYSTEM LOG', category:'SYSTEM', source:'WATCH+PC', desc:'Watch status plus unified PC event history.', actions:[{label:'EVENTS',command:'GET_EVENTS'},{label:'CLEAR UI',command:'LOG_CLEAR'}] },
  '26': { id:26, title:'MOTION COMMAND 2.0', category:'SMART', source:'WATCH', desc:'Trainable gesture baseline, sensitivity, confidence threshold and non-executing test mode.', actions:[{label:'ARM',command:'MOTION_ARM'},{label:'TRAIN',command:'MOTION_TRAIN'},{label:'SENS',command:'MOTION_SENS_CYCLE'},{label:'TEST',command:'MOTION_TEST_TOGGLE'}] },
  '31': { id:31, title:'VOICE COMMAND PRO 2.0', category:'SMART', source:'PHONE+PC', desc:'Aliases, context-aware voice intents, macros and confirmation for risky commands.', actions:[{label:'PUSH TO TALK',command:'VOICE_PTT'},{label:'CONTEXT',command:'GET_CONTEXT_PRO'}] },
  '39': { id:39, title:'WI-FI RECON PRO 2.0', category:'NETWORK', source:'PHONE', desc:'Signal history, channel congestion, band counts, heuristic security grade and roaming comparison.', actions:[{label:'SCAN',command:'WIFI_SCAN'},{label:'BEST',command:'WIFI_BEST'},{label:'ANALYZE',command:'WIFI_ANALYZE'},{label:'STATUS',command:'WIFI_STATUS'}] },
  '49': { id:49, title:'AUDIO MIXER PRO 2.0', category:'CONTROL', source:'PC', desc:'Master and per-app audio, favorite sessions and truthful output-switch capability.', actions:[{label:'REFRESH',command:'GET_AUDIO_PRO'},{label:'VOL -',command:'VOLUME_DOWN'},{label:'VOL +',command:'VOLUME_UP'},{label:'MUTE',command:'MEDIA_MUTE'}] },
  '50': { id:50, title:'WINDOW CENTER 2.0', category:'CONTROL', source:'PC', desc:'Window list, maximize/restore, snap left/right and move-to-monitor controls.', actions:[{label:'REFRESH',command:'GET_WINDOWS_PRO'},{label:'SNAP L',command:'WINDOW_SNAP_LEFT_ACTIVE'},{label:'SNAP R',command:'WINDOW_SNAP_RIGHT_ACTIVE'},{label:'MOVE',command:'WINDOW_MOVE_MONITOR_ACTIVE'}] },
  '51': { id:51, title:'MACRO DECK 2.0', category:'SMART', source:'PC', desc:'Safe structured multi-step workflows with delays, conditions, folders, favorites and cancel state.', actions:[{label:'REFRESH',command:'GET_MACROS_V2'},{label:'WORK',command:'MACRO_V2_RUN_WORK'},{label:'GAME',command:'MACRO_V2_RUN_GAME'},{label:'MEETING',command:'MACRO_V2_RUN_MEETING'}] },
  '52': { id:52, title:'NOTIFICATION BRIDGE 2.0', category:'SYSTEM', source:'PC', desc:'Critical/warning/info alerts with dedupe, acknowledgement, snooze, history and escalation.', actions:[{label:'REFRESH',command:'GET_NOTIFICATIONS_PRO'},{label:'ACK',command:'NOTIFICATION_ACK_LATEST'},{label:'SNOOZE',command:'NOTIFICATION_SNOOZE_LATEST'},{label:'CLEAR',command:'NOTIFICATION_CLEAR_PRO'}] },
  '53': { id:53, title:'TRUST CENTER 2.0', category:'SYSTEM', source:'PHONE+PC', desc:'Paired-device/session metadata, last access, token-rotation health and explicit revoke/rotation actions.', actions:[{label:'STATUS',command:'GET_TRUST_PRO'},{label:'PAIR',command:'PAIR_STATUS'},{label:'ROTATE',command:'TRUST_ROTATE_TOKEN_REQUEST'},{label:'REVOKE',command:'REVOKE_PC_LINK'}] },
  '54': { id:54, title:'PC CONTROL HUB', category:'CONTROL', source:'PC', desc:'Single operational overview linking Monitor, Mouse, Windows, Audio, Macros and Apps.', actions:[{label:'REFRESH',command:'GET_CONTROL_HUB'},{label:'MONITOR',command:'OPEN_FEATURE_1'},{label:'MOUSE',command:'OPEN_FEATURE_5'},{label:'WINDOWS',command:'OPEN_FEATURE_50'}] },
  '55': { id:55, title:'PC REMOTE SETTINGS', category:'SYSTEM', source:'PC+WATCH', desc:'Auto context, telemetry interval, notification threshold, profile, permissions and token-rotation policy.', actions:[{label:'REFRESH',command:'GET_PRO_SETTINGS'},{label:'PROFILE',command:'GET_PROFILES'},{label:'PERMS',command:'GET_PERMISSIONS'},{label:'TRUST',command:'GET_TRUST_PRO'}] }
};

export function getFeature(id){ return FEATURES[String(id)] || null; }

export function getFeaturesByCategory(category){
  var out=[];
  for(var k in FEATURES){
    if(FEATURES.hasOwnProperty(k) && FEATURES[k].category===category) out.push(FEATURES[k]);
  }
  return out;
}
