import app from '@system.app';
import battery from '@system.battery';
import vibrator from '@system.vibrator';
import sensor from '@system.sensor';
import { P2pClient, Message, Builder } from '../../wearengine/wearengine.js';
import { PHONE_PACKAGE, PHONE_FINGERPRINT } from '../../common/constants.js';
import { getFeature, getFeaturesByCategory } from '../../common/featureCatalog.js';

var p2pClient=new P2pClient(),msg=new Message(),builder=new Builder();
function cmdId(){return String(Date.now())+'-'+String(Math.floor(Math.random()*10000));}

export default {
  data:{
    view:'home',category:'CONTROL',categoryFeatures:[],connectionState:'OFFLINE',pcState:'UNKNOWN',watchBattery:0,clockText:'--:--',
    masterVolume:'--',cpu:'--',gpu:'--',ram:'--',ping:'--',quality:'OFFLINE',activeApp:'-',contextProfile:'DESKTOP',contextMode:'AUTO',
    selectedId:'',selectedTitle:'',selectedSource:'',selectedDesc:'',featureState:'READY',featureData:'-',visualMain:'READY',visualSub:'MODULE',
    action1Label:'',action2Label:'',action3Label:'',action4Label:'',action1Command:'',action2Command:'',action3Command:'',action4Command:'',
    message:'READY',commandState:'IDLE',commandId:'',lastAction:'',lastPayload:{},retryAllowed:false,clockTimer:null,
    dynamic1Label:'MONITOR',dynamic2Label:'MOUSE',dynamic3Label:'WINDOWS',dynamic4Label:'AUDIO',
    dynamic1Command:'OPEN_FEATURE_1',dynamic2Command:'OPEN_FEATURE_5',dynamic3Command:'OPEN_FEATURE_50',dynamic4Command:'OPEN_FEATURE_49',
    notificationCount:0,latestNotification:'-',latestNotificationId:'',audioOutput:'DEFAULT',currentWindowHwnd:0,currentMonitorIndex:0,
    historySummary:'NO HISTORY',topProcess:'NO PROCESS',macroState:'READY',appSummary:'NO APPS',wifiSummary:'NO SCAN',trustSummary:'SECURE',profileName:'WORK',settingsSummary:'DEFAULT',
    airMouseActive:false,airMousePrecision:false,airMouseDragging:false,airMouseSensitivity:5,airMouseCurve:'SMOOTH',airCalibrating:false,airCalCount:0,airBaseX:0,airBaseY:0,airNoise:0,airLast:0,
    motionArmed:false,motionTraining:false,motionTestMode:false,motionSensitivity:'NORMAL',motionConfidence:0,motionThreshold:85
  },
  onInit(){var s=this;this.refreshClock();this.clockTimer=setInterval(function(){s.refreshClock();},1000);this.refreshBattery();this.categoryFeatures=getFeaturesByCategory('CONTROL');this.setupWearEngine();},
  onDestroy(){if(this.clockTimer)clearInterval(this.clockTimer);this.stopMotion();this.stopAirMouse();try{p2pClient.unregisterReceiver({onSuccess:function(){},onFailure:function(){}});}catch(e){}},
  two(n){return n<10?'0'+n:String(n);},refreshClock(){var d=new Date();this.clockText=this.two(d.getHours())+':'+this.two(d.getMinutes());},
  refreshBattery(){var s=this;try{battery.getStatus({success:function(d){s.watchBattery=Math.round((d.level||0)*100);},fail:function(){}});}catch(e){}},
  haptic(m){try{vibrator.vibrate({mode:m||'short',success:function(){},fail:function(){}});}catch(e){}},
  compact(o){try{return (typeof o==='string'?o:JSON.stringify(o)).substring(0,180);}catch(e){return '-';}},
  setupWearEngine(){var s=this;try{p2pClient.setPeerPkgName(PHONE_PACKAGE);p2pClient.setPeerFingerPrint(PHONE_FINGERPRINT);p2pClient.registerReceiver({onSuccess:function(){s.connectionState='CONNECTED';s.message='PHONE LINK READY';s.sendRemote('GET_CONTROL_HUB',{});},onFailure:function(){s.connectionState='OFFLINE';s.pcState='OFFLINE';s.message='WEAR ENGINE OFFLINE';},onReceiveMessage:function(d){s.onPhoneMessage(d);}});}catch(e){this.message='INSTALL OFFICIAL WEAR ENGINE';}},
  onPhoneMessage(data){
    if(!data||data.isFileType)return;try{var raw=typeof data.data!=='undefined'?data.data:data,o=JSON.parse(String(raw));
      if(o.type==='lifecycle'){this.commandId=o.id||this.commandId;this.commandState=o.state||'RUNNING';this.message=(o.action||'COMMAND')+' '+this.commandState;if(this.commandState==='FAILED'||this.commandState==='TIMEOUT')this.haptic('long');return;}
      if(o.type==='snapshot'){if(o.pc)this.updateDashboard(o.pc);if(o.wifi)this.updateWifi(o.wifi);this.connectionState='CONNECTED';return;}
      if(o.type!=='result')return;this.commandId=o.id||this.commandId;this.commandState=o.commandState||(o.ok?'DONE':'FAILED');this.message=(o.ok?'DONE: ':'FAILED: ')+(o.message||o.action||'');this.featureState=o.ok?'READY':'ERROR';this.retryAllowed=!this.isRisky(this.lastAction);var a=o.action||'',d=o.data||{};
      if(a==='GET_DASHBOARD'||a==='GET_DASHBOARD_PRO'||a==='GET_PC_STATUS')this.updateDashboard(d);else if(a==='GET_CONTROL_HUB')this.updateHub(d);else if(a==='GET_TELEMETRY_HISTORY')this.updateHistory(d);else if(a==='GET_TOP_PROCESSES')this.updateProcesses(d);else if(a==='GET_NETWORK'||a==='NETWORK_PING')this.updateNetwork(d);else if(a.indexOf('CONTEXT_')===0||a==='GET_CONTEXT'||a==='GET_CONTEXT_PRO')this.updateContext(d);else if(a==='GET_WINDOWS'||a==='GET_WINDOWS_PRO'||a==='GET_MONITORS')this.updateWindows(d);else if(a==='GET_AUDIO'||a==='GET_AUDIO_PRO'||a.indexOf('AUDIO_')===0)this.updateAudio(d);else if(a==='GET_APPS'||a==='GET_APPS_PRO'||a==='APP_SMART')this.updateApps(d);else if(a==='GET_MACROS'||a==='GET_MACROS_V2'||a.indexOf('MACRO_V2_')===0)this.updateMacros(d,a);else if(a==='GET_NOTIFICATIONS'||a==='GET_NOTIFICATIONS_PRO'||a.indexOf('NOTIFICATION_')===0)this.updateNotifications(d);else if(a==='GET_TRUST_PRO'||a.indexOf('TRUST_')===0)this.updateTrust(d);else if(a==='GET_PRO_SETTINGS')this.updateSettings(d);else if(a==='GET_PROFILES'||a==='PROFILE_SET')this.profileName=d.active||d.profile||this.profileName;else if(typeof o.data!=='undefined')this.featureData=this.compact(o.data);
    }catch(e){this.message='RX DATA';}
  },
  updateDashboard(d){if(d.state)this.pcState=d.state;if(typeof d.cpuPercent==='number')this.cpu=d.cpuPercent+'%';if(typeof d.gpuPercent==='number')this.gpu=d.gpuPercent+'%';else if(d.hasOwnProperty('gpuPercent'))this.gpu='UNAVAILABLE';if(typeof d.ramPercent==='number')this.ram=d.ramPercent+'%';if(d.network&&typeof d.network.pingMs==='number')this.ping=d.network.pingMs+'ms';if(d.connectionQuality)this.quality=d.connectionQuality;if(d.activeApp)this.activeApp=d.activeApp;if(d.contextPro)this.updateContext(d.contextPro);else if(d.context)this.updateContext(d.context);if(d.audio)this.updateAudio(d.audio);if(d.history)this.updateHistory(d.history);if(typeof d.notificationCountPro==='number')this.notificationCount=d.notificationCountPro;if(d.latestNotificationPro){this.latestNotification=(d.latestNotificationPro.priority||'INFO')+' '+(d.latestNotificationPro.title||'ALERT');this.latestNotificationId=String(d.latestNotificationPro.id||'');}this.connectionState='CONNECTED';},
  updateHub(d){this.pcState=d.state||this.pcState;if(typeof d.cpu==='number')this.cpu=d.cpu+'%';if(typeof d.ram==='number')this.ram=d.ram+'%';if(typeof d.gpu==='number')this.gpu=d.gpu+'%';if(typeof d.pingMs==='number')this.ping=d.pingMs+'ms';this.quality=d.quality||this.quality;this.contextProfile=d.context||this.contextProfile;this.activeApp=d.activeApp||this.activeApp;this.profileName=d.profile||this.profileName;if(d.quickActions)this.applyDynamic(d.quickActions);this.featureData=this.pcState+' | '+this.cpu+' | '+this.contextProfile+' | '+this.activeApp;},
  updateHistory(d){var p=d.points||[];this.historySummary=p.length?p.length+' SAMPLES / '+String(d.seconds||300)+' SEC':'NO HISTORY';this.featureData=this.historySummary;},
  updateProcesses(d){var a=d.items||[];if(!d.available){this.topProcess='UNAVAILABLE';this.featureData=d.reason||'UNAVAILABLE';return;}if(a.length){this.topProcess=(a[0].name||'PROCESS')+' '+(d.metric||'CPU');this.featureData=this.topProcess+' | RAM '+String(a[0].ramMB||0)+' MB';}},
  updateNetwork(d){if(typeof d.pingMs==='number')this.ping=d.pingMs+'ms';this.featureData=(d.ip||'NO IP')+' | '+this.ping+' | ↓'+String(d.downloadMbps||0)+' ↑'+String(d.uploadMbps||0)+' Mbps';},
  updateContext(d){this.contextProfile=d.profile||this.contextProfile;this.contextMode=d.mode||this.contextMode;var a=d.active||{};this.activeApp=a.process||a.title||this.activeApp;if(d.actions)this.applyDynamic(d.actions);this.featureData=this.contextProfile+' | '+this.activeApp;},
  applyDynamic(a){if(!a||!a.length)return;this.dynamic1Label=a[0]||'ACTION 1';this.dynamic2Label=a[1]||'ACTION 2';this.dynamic3Label=a[2]||'ACTION 3';this.dynamic4Label=a[3]||'ACTION 4';this.dynamic1Command='CONTEXT_SLOT_1';this.dynamic2Command='CONTEXT_SLOT_2';this.dynamic3Command='CONTEXT_SLOT_3';this.dynamic4Command='CONTEXT_SLOT_4';},
  updateWindows(d){var a=d.active||{},w=d.windows||[],m=d.monitors||[];this.currentWindowHwnd=Number(a.hwnd||0);this.featureData=(a.title||a.process||'NO ACTIVE')+' | '+w.length+' WINDOWS | '+m.length+' MONITORS';},
  updateAudio(d){this.audioOutput=d.output||this.audioOutput;if(typeof d.master==='number')this.masterVolume=String(Math.round(d.master));this.featureData=this.audioOutput+' | '+(d.sessions||[]).length+' SESSIONS'+(d.outputSwitchAvailable===false?' | OUTPUT SWITCH UNAVAILABLE':'');},
  updateApps(d){var a=d.apps||[],n=[];for(var i=0;i<a.length;i++)n.push((a[i].running?'● ':'○ ')+(a[i].name||a[i].id));this.appSummary=n.slice(0,5).join(' / ')||'NO APPS';this.featureData=this.appSummary;},
  updateMacros(d,a){if(a&&a.indexOf('RUN')>=0)this.macroState=d.state||'DONE';var m=d.macros||d,n=[];if(m&&typeof m==='object')for(var k in m)if(m.hasOwnProperty(k)&&typeof m[k]==='object')n.push(m[k].name||k);this.featureData=n.slice(0,5).join(' / ')||this.compact(d);},
  updateNotifications(d){var a=d.items||[];this.notificationCount=Number(d.count||a.length||this.notificationCount||0);if(a.length){this.latestNotification=(a[0].priority||'INFO')+' '+(a[0].title||'ALERT')+': '+(a[0].message||'');this.latestNotificationId=String(a[0].id||'');}this.featureData=this.notificationCount+' ALERTS | '+this.latestNotification;},
  updateWifi(w){var x='';if(w.best&&w.best.ssid)x=' | BEST '+w.best.ssid+' '+String(w.best.score||0);if(w.channelAnalysis)x+=' | CH '+String(w.channelAnalysis.recommended||'--');this.wifiSummary=(w.summary||'WI-FI SYNC')+x;this.featureData=this.wifiSummary;},
  updateTrust(d){var t=d.token||{};this.trustSummary=(d.status||'TRUSTED')+' | SESSION '+String(d.sessionAgeSeconds||0)+'s | TOKEN '+(t.status||'UNKNOWN');this.featureData=this.trustSummary;},
  updateSettings(d){this.profileName=d.profile||this.profileName;this.contextMode=d.context_mode||this.contextMode;this.motionThreshold=Number(d.motion_confidence_threshold||this.motionThreshold);this.settingsSummary='PROFILE '+this.profileName+' | CONTEXT '+this.contextMode+' | '+String(d.telemetry_interval_seconds||'--')+' SEC';this.featureData=this.settingsSummary;},
  isRisky(a){return a==='SYSTEM_SHUTDOWN'||a==='SYSTEM_RESTART'||a==='SYSTEM_SLEEP'||a==='WINDOW_CLOSE'||a==='TRUST_ROTATE_TOKEN';},
  requiresPc(a){if(!a||a==='VOICE_PTT'||a==='PAIR_STATUS'||a==='REVOKE_PC_LINK'||a.indexOf('WIFI_')===0||a.indexOf('PHONE_')===0||a.indexOf('IOT_')===0||a.indexOf('OBS_')===0||a.indexOf('OPEN_FEATURE_')===0)return false;return true;},
  sendCommand(a,p){if(!a)return;if(a.indexOf('OPEN_FEATURE_')===0){this.openFeature(a.replace('OPEN_FEATURE_',''));return;}if(a==='AIR_MOUSE_START'){this.startAirMouse();return;}if(a==='AIR_MOUSE_PRECISION'){this.airMousePrecision=!this.airMousePrecision;this.featureData=this.airMousePrecision?'PRECISION ×0.25':'NORMAL ×1.0';return;}if(a==='AIR_MOUSE_DRAG_TOGGLE'){this.toggleDrag();return;}if(a==='AIR_MOUSE_DOUBLE'){this.sendRemote('MOUSE_DOUBLE',{});return;}if(a==='MOTION_ARM'){this.startMotion();return;}if(a==='MOTION_TRAIN'){this.trainMotion();return;}if(a==='MOTION_SENS_CYCLE'){this.cycleMotionSensitivity();return;}if(a==='MOTION_TEST_TOGGLE'){this.motionTestMode=!this.motionTestMode;this.featureData='TEST '+(this.motionTestMode?'READY':'OFF');return;}if(a==='CONTEXT_MODE_AUTO'){this.sendRemote('CONTEXT_SET_MODE',{mode:'AUTO',locked:false});return;}if(a==='CONTEXT_MODE_MANUAL'){this.sendRemote('CONTEXT_SET_MODE',{mode:'MANUAL',locked:false});return;}if(a==='CONTEXT_LOCK_TOGGLE'){this.sendRemote('CONTEXT_SET_MODE',{mode:this.contextMode,locked:true});return;}if(a==='APP_SMART_CHROME'){this.sendRemote('APP_SMART',{id:'chrome'});return;}if(a==='APP_SMART_VSCODE'){this.sendRemote('APP_SMART',{id:'vscode'});return;}if(a==='APP_SMART_STEAM'){this.sendRemote('APP_SMART',{id:'steam'});return;}if(a==='WINDOW_SNAP_LEFT_ACTIVE'||a==='WINDOW_SNAP_RIGHT_ACTIVE'||a==='WINDOW_MOVE_MONITOR_ACTIVE'){if(!this.currentWindowHwnd){this.message='REFRESH WINDOWS FIRST';return;}if(a==='WINDOW_SNAP_LEFT_ACTIVE')this.sendRemote('WINDOW_SNAP_LEFT',{hwnd:this.currentWindowHwnd});else if(a==='WINDOW_SNAP_RIGHT_ACTIVE')this.sendRemote('WINDOW_SNAP_RIGHT',{hwnd:this.currentWindowHwnd});else this.sendRemote('WINDOW_MOVE_MONITOR',{hwnd:this.currentWindowHwnd,monitor:this.currentMonitorIndex+1});return;}if(a==='MACRO_V2_RUN_WORK'){this.sendRemote('MACRO_V2_RUN',{id:'work'});return;}if(a==='MACRO_V2_RUN_GAME'){this.sendRemote('MACRO_V2_RUN',{id:'game'});return;}if(a==='MACRO_V2_RUN_MEETING'){this.sendRemote('MACRO_V2_RUN',{id:'meeting'});return;}if(a==='NOTIFICATION_ACK_LATEST'){if(this.latestNotificationId)this.sendRemote('NOTIFICATION_ACK',{id:this.latestNotificationId});return;}if(a==='NOTIFICATION_SNOOZE_LATEST'){if(this.latestNotificationId)this.sendRemote('NOTIFICATION_SNOOZE',{id:this.latestNotificationId,minutes:15});return;}if(a==='TRUST_ROTATE_TOKEN_REQUEST'){this.sendRemote('TRUST_ROTATE_TOKEN_REQUEST',{});return;}if(a==='LOG_CLEAR'){this.featureData='-';this.message='WATCH LOG CLEARED';return;}this.sendRemote(a,p||{});},
  sendRemote(a,p){if(this.requiresPc(a)&&this.pcState==='OFFLINE'){this.commandState='FAILED';this.message='PC OFFLINE';this.retryAllowed=!this.isRisky(a);return;}var s=this,id=cmdId(),body=p||{};this.commandId=id;this.commandState='SENDING';this.lastAction=a;this.lastPayload=body;this.retryAllowed=false;var e={v:2,id:id,ts:Date.now(),type:'command',action:a,source:'FIT4PRO',payload:body};try{builder.setDescription(JSON.stringify(e));msg.builder=builder;p2pClient.send(msg,{onSuccess:function(){s.connectionState='CONNECTED';s.message='SENT '+a;},onFailure:function(){s.connectionState='OFFLINE';s.commandState='FAILED';s.message='PHONE LINK FAILED';s.retryAllowed=!s.isRisky(a);s.haptic('long');},onSendResult:function(r){if(r&&r.code&&r.code!=207)s.message='SEND CODE '+r.code;},onSendProgress:function(){}});}catch(x){this.connectionState='OFFLINE';this.commandState='FAILED';this.message='OFFLINE: '+a;this.retryAllowed=!this.isRisky(a);}},
  retryLast(){if(!this.retryAllowed||!this.lastAction||this.isRisky(this.lastAction)){this.message='RETRY NOT AVAILABLE';return;}this.sendRemote(this.lastAction,this.lastPayload||{});},

  airState:{sumX:0,sumY:0,sumNoise:0,lastX:0,lastY:0},
  startAirMouse(){var s=this;if(this.airMouseActive)return;this.stopMotion();this.airMouseActive=true;this.airCalibrating=true;this.airCalCount=0;this.airState={sumX:0,sumY:0,sumNoise:0,lastX:0,lastY:0};this.featureState='CALIBRATING';this.featureData='KEEP WRIST STILL';try{sensor.subscribeGyroscope({interval:'ui',success:function(r){s.onAirGyro(r);},fail:function(d,c){s.airMouseActive=false;s.featureState='NO PERMISSION';}});}catch(e){this.featureState='UNAVAILABLE';}},
  stopAirMouse(){if(!this.airMouseActive)return;if(this.airMouseDragging)this.sendRemote('MOUSE_LEFT_UP',{});try{sensor.unsubscribeGyroscope();}catch(e){}this.airMouseActive=false;this.airMouseDragging=false;this.featureState='READY';},
  toggleDrag(){if(!this.airMouseActive){this.message='START AIR MOUSE FIRST';return;}this.airMouseDragging=!this.airMouseDragging;this.sendRemote(this.airMouseDragging?'MOUSE_LEFT_DOWN':'MOUSE_LEFT_UP',{});this.featureData=this.airMouseDragging?'DRAGGING':'DRAG OFF';},
  curve(v){var sign=v<0?-1:1,x=Math.abs(v);if(this.airMouseCurve==='FAST')return sign*x*x*1.25;if(this.airMouseCurve==='LINEAR')return v;if(this.airMouseCurve==='PRECISION')return sign*Math.sqrt(x)*.55;return sign*(x<.8?x*.65:x*x*.85);},
  onAirGyro(r){var x=Number(r.y||0),y=Number(r.x||0),st=this.airState;if(this.airCalibrating){st.sumX+=x;st.sumY+=y;if(this.airCalCount>0)st.sumNoise+=Math.sqrt((x-st.lastX)*(x-st.lastX)+(y-st.lastY)*(y-st.lastY));st.lastX=x;st.lastY=y;this.airCalCount++;this.featureData='CALIBRATING '+this.airCalCount+'/20';if(this.airCalCount>=20){this.airBaseX=st.sumX/20;this.airBaseY=st.sumY/20;this.airNoise=st.sumNoise/19;this.airCalibrating=false;this.featureState='ACTIVE';this.featureData='READY | NOISE '+this.airNoise.toFixed(2);}return;}var now=Date.now();if(now-this.airLast<100)return;this.airLast=now;x-=this.airBaseX;y-=this.airBaseY;var dead=Math.max(.12,Math.min(.35,.14+this.airNoise*.45));if(Math.abs(x)<dead)x=0;if(Math.abs(y)<dead)y=0;if(!x&&!y)return;x=this.curve(x);y=this.curve(y);var f=this.airMousePrecision?.25:1,s=this.airMouseSensitivity,dx=Math.round(x*s*2.4*f),dy=Math.round(y*s*2.4*f);dx=Math.max(-40,Math.min(40,dx));dy=Math.max(-40,Math.min(40,dy));this.sendRemote('MOUSE_MOVE',{dx:dx,dy:dy,precision:this.airMousePrecision,curve:this.airMouseCurve});},

  motionState:{baseX:0,baseY:0,baseZ:0,count:0,sumX:0,sumY:0,sumZ:0,lastGesture:0,lastTwist:0,twists:0,shakes:0,shakeWindow:0},
  startMotion(){var s=this;if(this.motionArmed)return;this.stopAirMouse();this.motionArmed=true;try{sensor.subscribeAccelerometer({interval:'ui',success:function(r){s.onAccel(r);},fail:function(){s.motionArmed=false;s.featureState='NO PERMISSION';}});sensor.subscribeGyroscope({interval:'ui',success:function(r){s.onMotionGyro(r);},fail:function(){}});}catch(e){this.motionArmed=false;this.featureState='UNAVAILABLE';}},
  stopMotion(){try{sensor.unsubscribeAccelerometer();}catch(e){}try{if(!this.airMouseActive)sensor.unsubscribeGyroscope();}catch(e){}this.motionArmed=false;this.motionTraining=false;},
  trainMotion(){var st=this.motionState;st.count=0;st.sumX=0;st.sumY=0;st.sumZ=0;this.motionTraining=true;this.featureData='TRAIN 0/30';if(!this.motionArmed)this.startMotion();},
  cycleMotionSensitivity(){var a=['LOW','NORMAL','HIGH','CUSTOM'],i=(a.indexOf(this.motionSensitivity)+1)%a.length;this.motionSensitivity=a[i];this.featureData='SENS '+this.motionSensitivity+' | '+this.motionThreshold+'%';},
  motionTh(){return this.motionSensitivity==='LOW'?14:this.motionSensitivity==='HIGH'?9:11;},
  onAccel(r){var st=this.motionState,x=Number(r.x||0),y=Number(r.y||0),z=Number(r.z||0);if(this.motionTraining){st.sumX+=x;st.sumY+=y;st.sumZ+=z;st.count++;this.featureData='TRAIN '+st.count+'/30';if(st.count>=30){st.baseX=st.sumX/30;st.baseY=st.sumY/30;st.baseZ=st.sumZ/30;this.motionTraining=false;this.featureData='BASELINE SAVED';}return;}var now=Date.now();if(now-st.lastGesture<800)return;var dx=x-st.baseX,dy=y-st.baseY,dz=z-st.baseZ,mag=Math.sqrt(dx*dx+dy*dy+dz*dz),th=this.motionTh();if(dx>th&&Math.abs(dy)<th){this.motionGesture('RIGHT FLICK','CONTEXT_SLOT_2',Math.min(99,Math.round(68+dx*2.2)));return;}if(dx<-th&&Math.abs(dy)<th){this.motionGesture('LEFT FLICK','CONTEXT_SLOT_1',Math.min(99,Math.round(68+Math.abs(dx)*2.2)));return;}if(mag>th+7){if(now-st.shakeWindow>700){st.shakeWindow=now;st.shakes=0;}st.shakes++;if(st.shakes>=3){st.shakes=0;this.motionGesture('SHAKE','MEDIA_MUTE',92);}}},
  onMotionGyro(r){var st=this.motionState,now=Date.now(),z=Math.abs(Number(r.z||0));if(z>3){st.twists=now-st.lastTwist<700?st.twists+1:1;st.lastTwist=now;if(st.twists>=2&&now-st.lastGesture>800){st.twists=0;this.motionGesture('DOUBLE TWIST','MEDIA_PLAY_PAUSE',90);}}},
  motionGesture(n,c,conf){this.motionConfidence=conf;this.featureData=n+' | CONFIDENCE '+conf+'%';if(conf<this.motionThreshold){this.message='GESTURE IGNORED';return;}this.motionState.lastGesture=Date.now();this.haptic('short');if(this.motionTestMode){this.message='TEST DETECTED '+n;return;}this.sendRemote(c,{gesture:n,confidence:conf,context:this.contextProfile});},

  visualFor(id){var n=String(id);if(n==='1')return[this.cpu,'PC MONITOR'];if(n==='4')return[this.contextProfile,'CONTEXT'];if(n==='5')return[this.airMousePrecision?'PREC':'GYRO','AIR MOUSE'];if(n==='6')return['APPS','SMART LAUNCH'];if(n==='12')return[this.ping,'NETWORK'];if(n==='21'||n==='54')return[this.pcState,'CONTROL HUB'];if(n==='26')return[String(this.motionConfidence)+'%','MOTION'];if(n==='39')return['WI-FI','RECON 2.0'];if(n==='49')return[this.masterVolume+'%','AUDIO'];if(n==='50')return['WINDOW','CENTER'];if(n==='51')return[this.macroState,'MACRO'];if(n==='52')return[String(this.notificationCount),'ALERTS'];if(n==='53')return['TRUST','SECURITY'];if(n==='55')return[this.profileName,'SETTINGS'];return['READY','MODULE'];},
  openFeature(id){var f=getFeature(id);if(!f)return;this.selectedId=String(id);this.selectedTitle=f.title;this.selectedSource=f.source;this.selectedDesc=f.desc;for(var i=0;i<4;i++){var a=f.actions[i]||{label:'',command:''};this['action'+(i+1)+'Label']=a.label;this['action'+(i+1)+'Command']=a.command;}var v=this.visualFor(id);this.visualMain=v[0];this.visualSub=v[1];this.featureState='READY';this.featureData='-';this.view='detail';var n=String(id),q=n==='1'?'GET_DASHBOARD_PRO':n==='4'?'GET_CONTEXT_PRO':n==='6'?'GET_APPS_PRO':n==='12'?'GET_NETWORK':n==='21'||n==='54'?'GET_CONTROL_HUB':n==='39'?'WIFI_SCAN':n==='49'?'GET_AUDIO_PRO':n==='50'?'GET_WINDOWS_PRO':n==='51'?'GET_MACROS_V2':n==='52'?'GET_NOTIFICATIONS_PRO':n==='53'?'GET_TRUST_PRO':n==='55'?'GET_PRO_SETTINGS':'';if(q)this.sendRemote(q,{});},
  setCategory(c){this.category=c;this.categoryFeatures=getFeaturesByCategory(c);this.view='list';},goHome(){this.view='home';this.sendRemote('GET_CONTROL_HUB',{});},goList(){this.setCategory(this.category);},catControl(){this.setCategory('CONTROL');},catApps(){this.setCategory('APPS');},catSmart(){this.setCategory('SMART');},catNetwork(){this.setCategory('NETWORK');},catSystem(){this.setCategory('SYSTEM');},
  featureTap(e){var id='';try{id=String(e.target.attr.dataId||e.target.dataId||'');}catch(x){}if(!id&&e&&e.detail&&typeof e.detail.id!=='undefined')id=String(e.detail.id);if(id)this.openFeature(id);},
  quickPlay(){this.sendCommand('MEDIA_PLAY_PAUSE');},quickMute(){this.sendCommand('MEDIA_MUTE');},quickLock(){this.sendCommand('PC_LOCK');},quickShot(){this.sendCommand('SCREENSHOT');},dynamic1(){this.sendCommand(this.dynamic1Command);},dynamic2(){this.sendCommand(this.dynamic2Command);},dynamic3(){this.sendCommand(this.dynamic3Command);},dynamic4(){this.sendCommand(this.dynamic4Command);},detailAction1(){this.sendCommand(this.action1Command);},detailAction2(){this.sendCommand(this.action2Command);},detailAction3(){this.sendCommand(this.action3Command);},detailAction4(){this.sendCommand(this.action4Command);},
  swipeEvent(e){if(e.direction==='right'){if(this.view==='home')app.terminate();else if(this.view==='detail')this.goList();else this.goHome();}}
};
