plugins { id 'com.android.application' }

android {
    namespace 'com.riptwosec.pcremotedeck'
    compileSdk 35
    defaultConfig {
        applicationId 'com.riptwosec.pcremotedeck'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '6.1-fit4pro'
        buildConfigField 'String', 'WATCH_PACKAGE', '"com.riptwosec.pcremotedeck.watch"'
        buildConfigField 'String', 'WATCH_FINGERPRINT', '"REPLACE_WITH_WATCH_SHA256_FINGERPRINT"'
    }
    buildFeatures { buildConfig true }
}

dependencies {
    implementation 'com.huawei.hms:wearengine:5.0.2.306'
}
